import {
  OSCFormula,
  ScentCard,
  UserProfile,
  IngredientDatabaseEntry,
  HistoryEntry,
} from "./types";

// -------------------------------------------------------------------
// INGREDIENT DATABASE (100+ entries)
// -------------------------------------------------------------------

export const ingredientDatabase: IngredientDatabaseEntry[] = [
  // CITRUS
  { name: "Bergamot", cas_number: "8007-75-8", category: "citrus", note_type: "top", typical_percentage_range: { min: 3, max: 20 }, volatility: "high", description: "Bright, slightly floral citrus with a green, tea-like nuance", common_pairings: ["Lavender", "Rose", "Neroli", "Jasmine"] },
  { name: "Lemon", cas_number: "8008-56-8", category: "citrus", note_type: "top", typical_percentage_range: { min: 2, max: 15 }, volatility: "high", description: "Clean, sharp, zesty citrus with a fresh sparkle", common_pairings: ["Basil", "Thyme", "Verbena", "Ginger"] },
  { name: "Orange", cas_number: "8008-57-9", category: "citrus", note_type: "top", typical_percentage_range: { min: 3, max: 20 }, volatility: "high", description: "Sweet, juicy, radiant citrus warmth", common_pairings: ["Cinnamon", "Vanilla", "Neroli", "Chocolate"] },
  { name: "Grapefruit", cas_number: "8016-20-4", category: "citrus", note_type: "top", typical_percentage_range: { min: 2, max: 12 }, volatility: "high", description: "Tangy, bitter-sweet citrus with a sparkling edge", common_pairings: ["Mint", "Rosemary", "Black Pepper", "Vetiver"] },
  { name: "Lime", cas_number: "8008-26-2", category: "citrus", note_type: "top", typical_percentage_range: { min: 2, max: 10 }, volatility: "high", description: "Sharp, green, effervescent citrus", common_pairings: ["Coconut", "Ginger", "Basil", "Mint"] },
  { name: "Yuzu", cas_number: "N/A-yuzu", category: "citrus", note_type: "top", typical_percentage_range: { min: 1, max: 8 }, volatility: "high", description: "Complex Japanese citrus, tart and floral", common_pairings: ["Green Tea", "Hinoki", "Shiso", "Ginger"] },
  { name: "Mandarin", cas_number: "8008-31-9", category: "citrus", note_type: "top", typical_percentage_range: { min: 3, max: 15 }, volatility: "high", description: "Sweet, soft, child-like citrus warmth", common_pairings: ["Neroli", "Petitgrain", "Cinnamon", "Musk"] },
  { name: "Petitgrain", cas_number: "8014-17-3", category: "citrus", note_type: "top", typical_percentage_range: { min: 2, max: 12 }, volatility: "high", description: "Green, woody-citrus with a bitter-sweet edge", common_pairings: ["Neroli", "Lavender", "Rosemary", "Clary Sage"] },

  // FLORAL
  { name: "Rose", cas_number: "8007-01-0", category: "floral", note_type: "middle", typical_percentage_range: { min: 3, max: 25 }, volatility: "medium", description: "Rich, honeyed, classic floral with depth and complexity", common_pairings: ["Oud", "Saffron", "Patchouli", "Bergamot"] },
  { name: "Jasmine", cas_number: "8022-96-6", category: "floral", note_type: "middle", typical_percentage_range: { min: 3, max: 20 }, volatility: "medium", description: "Intensely sweet, sensual white floral with fruity nuances", common_pairings: ["Sandalwood", "Vanilla", "Bergamot", "Tuberose"] },
  { name: "Ylang Ylang", cas_number: "8006-81-3", category: "floral", note_type: "middle", typical_percentage_range: { min: 2, max: 12 }, volatility: "medium", description: "Exotic, creamy, custard-like tropical floral", common_pairings: ["Vetiver", "Sandalwood", "Coconut", "Bergamot"] },
  { name: "Tuberose", cas_number: "8024-55-3", category: "floral", note_type: "middle", typical_percentage_range: { min: 2, max: 15 }, volatility: "medium", description: "Heady, opulent, narcotic white floral", common_pairings: ["Gardenia", "Coconut", "Sandalwood", "Musk"] },
  { name: "Iris", cas_number: "8002-73-1", category: "floral", note_type: "middle", typical_percentage_range: { min: 1, max: 10 }, volatility: "medium", description: "Powdery, elegant, cool violet-like floral", common_pairings: ["Violet", "Rose", "Cedar", "Musk"] },
  { name: "Violet", cas_number: "8024-08-6", category: "floral", note_type: "middle", typical_percentage_range: { min: 1, max: 8 }, volatility: "medium", description: "Soft, powdery, sweet floral with green leaf aspects", common_pairings: ["Iris", "Rose", "Vanilla", "Musk"] },
  { name: "Lily of the Valley", cas_number: "N/A-lotv", category: "floral", note_type: "middle", typical_percentage_range: { min: 2, max: 12 }, volatility: "medium", description: "Dewy, green, delicate spring floral", common_pairings: ["Rose", "Jasmine", "Muguet", "Green Tea"] },
  { name: "Magnolia", cas_number: "N/A-mag", category: "floral", note_type: "middle", typical_percentage_range: { min: 2, max: 10 }, volatility: "medium", description: "Creamy, champagne-like, lush white floral", common_pairings: ["Peony", "Pear", "Sandalwood", "Musk"] },
  { name: "Neroli", cas_number: "8016-38-4", category: "floral", note_type: "top", typical_percentage_range: { min: 2, max: 15 }, volatility: "high", description: "Bright, honeyed orange blossom with green aspects", common_pairings: ["Bergamot", "Petitgrain", "Musk", "Amber"] },
  { name: "Osmanthus", cas_number: "N/A-osm", category: "floral", note_type: "middle", typical_percentage_range: { min: 1, max: 8 }, volatility: "medium", description: "Apricot-like, leathery, suede-smooth floral", common_pairings: ["Suede", "Peach", "Tea", "Oud"] },
  { name: "Gardenia", cas_number: "N/A-gar", category: "floral", note_type: "middle", typical_percentage_range: { min: 2, max: 12 }, volatility: "medium", description: "Creamy, rich, tropical white floral", common_pairings: ["Tuberose", "Coconut", "Ylang Ylang", "Sandalwood"] },
  { name: "Peony", cas_number: "N/A-peo", category: "floral", note_type: "middle", typical_percentage_range: { min: 2, max: 10 }, volatility: "medium", description: "Light, fresh, dewy rose-like floral", common_pairings: ["Rose", "Magnolia", "Pear", "Musk"] },
  { name: "Geranium", cas_number: "8000-46-2", category: "floral", note_type: "middle", typical_percentage_range: { min: 2, max: 12 }, volatility: "medium", description: "Rosy-green, minty, slightly spicy floral", common_pairings: ["Rose", "Citronella", "Lavender", "Patchouli"] },
  { name: "Lavender", cas_number: "8000-28-0", category: "floral", note_type: "top", typical_percentage_range: { min: 3, max: 20 }, volatility: "high", description: "Aromatic, herbaceous, clean, calming floral", common_pairings: ["Bergamot", "Rosemary", "Vanilla", "Tonka Bean"] },

  // WOODY
  { name: "Sandalwood", cas_number: "8006-87-9", category: "woody", note_type: "base", typical_percentage_range: { min: 5, max: 25 }, volatility: "low", description: "Creamy, warm, milky, soft wood with a meditative quality", common_pairings: ["Rose", "Jasmine", "Vanilla", "Musk"] },
  { name: "Cedar", cas_number: "8000-27-9", category: "woody", note_type: "base", typical_percentage_range: { min: 5, max: 20 }, volatility: "low", description: "Dry, pencil-shaving wood with a clean, balsamic edge", common_pairings: ["Vetiver", "Bergamot", "Iris", "Patchouli"] },
  { name: "Vetiver", cas_number: "8016-96-4", category: "woody", note_type: "base", typical_percentage_range: { min: 3, max: 15 }, volatility: "low", description: "Earthy, smoky, complex root with green and woody facets", common_pairings: ["Grapefruit", "Iris", "Bergamot", "Oud"] },
  { name: "Oud", cas_number: "N/A-oud", category: "woody", note_type: "base", typical_percentage_range: { min: 1, max: 10 }, volatility: "low", description: "Complex, animalic, smoky, resinous precious wood", common_pairings: ["Rose", "Saffron", "Amber", "Sandalwood"] },
  { name: "Patchouli", cas_number: "8014-09-3", category: "woody", note_type: "base", typical_percentage_range: { min: 3, max: 20 }, volatility: "low", description: "Dark, earthy, sweet, slightly camphoraceous wood", common_pairings: ["Vanilla", "Rose", "Bergamot", "Chocolate"] },
  { name: "Guaiac Wood", cas_number: "8016-23-7", category: "woody", note_type: "base", typical_percentage_range: { min: 2, max: 12 }, volatility: "low", description: "Smoky, tea-like, rosy woody note", common_pairings: ["Vetiver", "Rose", "Incense", "Iris"] },
  { name: "Birch", cas_number: "8001-88-5", category: "woody", note_type: "base", typical_percentage_range: { min: 1, max: 8 }, volatility: "low", description: "Smoky, tar-like, leathery woody note", common_pairings: ["Leather", "Smoke", "Vetiver", "Cedar"] },
  { name: "Cypress", cas_number: "8013-86-3", category: "woody", note_type: "middle", typical_percentage_range: { min: 2, max: 10 }, volatility: "medium", description: "Fresh, clean, slightly coniferous green wood", common_pairings: ["Juniper", "Pine", "Bergamot", "Lavender"] },
  { name: "Pine", cas_number: "8002-09-3", category: "woody", note_type: "top", typical_percentage_range: { min: 2, max: 10 }, volatility: "high", description: "Sharp, fresh, resinous conifer", common_pairings: ["Eucalyptus", "Cedar", "Moss", "Juniper"] },
  { name: "Juniper", cas_number: "8002-68-4", category: "woody", note_type: "top", typical_percentage_range: { min: 2, max: 8 }, volatility: "high", description: "Gin-like, crisp, aromatic berry-wood", common_pairings: ["Cypress", "Bergamot", "Pine", "Lavender"] },
  { name: "Hinoki", cas_number: "N/A-hin", category: "woody", note_type: "base", typical_percentage_range: { min: 2, max: 12 }, volatility: "low", description: "Clean, lemon-tinged Japanese cypress", common_pairings: ["Yuzu", "Green Tea", "Incense", "Cedar"] },

  // ORIENTAL
  { name: "Vanilla", cas_number: "8024-06-4", category: "oriental", note_type: "base", typical_percentage_range: { min: 3, max: 20 }, volatility: "low", description: "Warm, sweet, comforting, universally beloved base", common_pairings: ["Sandalwood", "Tonka Bean", "Benzoin", "Amber"] },
  { name: "Benzoin", cas_number: "9000-05-9", category: "oriental", note_type: "base", typical_percentage_range: { min: 2, max: 10 }, volatility: "low", description: "Sweet, balsamic, vanillic resin", common_pairings: ["Vanilla", "Styrax", "Cinnamon", "Labdanum"] },
  { name: "Tonka Bean", cas_number: "8046-22-8", category: "oriental", note_type: "base", typical_percentage_range: { min: 2, max: 12 }, volatility: "low", description: "Warm, almond-like, hay, sweet coumarin richness", common_pairings: ["Lavender", "Vanilla", "Tobacco", "Amber"] },
  { name: "Labdanum", cas_number: "8016-26-0", category: "oriental", note_type: "base", typical_percentage_range: { min: 2, max: 10 }, volatility: "low", description: "Dark, ambery, leathery, warm resin", common_pairings: ["Amber", "Oud", "Cistus", "Patchouli"] },
  { name: "Styrax", cas_number: "8024-01-9", category: "oriental", note_type: "base", typical_percentage_range: { min: 1, max: 6 }, volatility: "low", description: "Sweet, balsamic, cinnamon-like resin", common_pairings: ["Benzoin", "Cinnamon", "Vanilla", "Incense"] },
  { name: "Coumarin", cas_number: "91-64-5", category: "oriental", note_type: "base", typical_percentage_range: { min: 1, max: 8 }, volatility: "low", description: "Warm, hay-like, sweet, almond nuance", common_pairings: ["Tonka Bean", "Lavender", "Vanilla", "Tobacco"] },

  // FRESH
  { name: "Aldehydes", cas_number: "N/A-ald", category: "fresh", note_type: "top", typical_percentage_range: { min: 1, max: 5 }, volatility: "high", description: "Sparkling, clean, soapy, effervescent freshness", common_pairings: ["Rose", "Jasmine", "Ylang Ylang", "Musk"] },
  { name: "Ozonic Notes", cas_number: "N/A-ozone", category: "fresh", note_type: "top", typical_percentage_range: { min: 1, max: 5 }, volatility: "high", description: "Clean, airy, post-rain atmosphere", common_pairings: ["Marine Notes", "Water Lily", "Iris", "Musk"] },
  { name: "Cucumber", cas_number: "N/A-cuc", category: "fresh", note_type: "top", typical_percentage_range: { min: 1, max: 5 }, volatility: "high", description: "Cool, green, aqueous freshness", common_pairings: ["Mint", "Green Tea", "Melon", "Violet Leaf"] },
  { name: "Green Tea", cas_number: "N/A-gtea", category: "fresh", note_type: "top", typical_percentage_range: { min: 2, max: 10 }, volatility: "high", description: "Light, clean, slightly bitter, calming", common_pairings: ["Jasmine", "Bergamot", "Mint", "Yuzu"] },
  { name: "Bamboo", cas_number: "N/A-bam", category: "fresh", note_type: "top", typical_percentage_range: { min: 1, max: 6 }, volatility: "high", description: "Clean, green, watery, zen-like freshness", common_pairings: ["Green Tea", "Lotus", "Linen", "White Musk"] },
  { name: "Fig Leaf", cas_number: "N/A-fig", category: "fresh", note_type: "top", typical_percentage_range: { min: 2, max: 8 }, volatility: "high", description: "Green, milky, woody, Mediterranean freshness", common_pairings: ["Coconut", "Cedar", "Bergamot", "Cassis"] },

  // AROMATIC
  { name: "Thyme", cas_number: "8007-46-3", category: "aromatic", note_type: "top", typical_percentage_range: { min: 1, max: 6 }, volatility: "high", description: "Herbal, medicinal, warm aromatic green", common_pairings: ["Lavender", "Rosemary", "Bergamot", "Lemon"] },
  { name: "Rosemary", cas_number: "8000-25-7", category: "aromatic", note_type: "top", typical_percentage_range: { min: 2, max: 8 }, volatility: "high", description: "Camphoraceous, herbal, invigorating green", common_pairings: ["Lavender", "Bergamot", "Grapefruit", "Cedar"] },
  { name: "Basil", cas_number: "8015-73-4", category: "aromatic", note_type: "top", typical_percentage_range: { min: 1, max: 5 }, volatility: "high", description: "Sweet, spicy, anise-like herbal freshness", common_pairings: ["Lime", "Bergamot", "Mint", "Ginger"] },
  { name: "Sage", cas_number: "8022-56-8", category: "aromatic", note_type: "top", typical_percentage_range: { min: 1, max: 6 }, volatility: "high", description: "Camphoraceous, dry, herbal, silvery-green", common_pairings: ["Lavender", "Bergamot", "Rosemary", "Cedar"] },
  { name: "Oregano", cas_number: "8007-11-2", category: "aromatic", note_type: "top", typical_percentage_range: { min: 0.5, max: 3 }, volatility: "high", description: "Warm, spicy, herbaceous Mediterranean note", common_pairings: ["Thyme", "Lavender", "Rosemary", "Bergamot"] },
  { name: "Mint", cas_number: "8006-90-4", category: "aromatic", note_type: "top", typical_percentage_range: { min: 2, max: 10 }, volatility: "high", description: "Cool, fresh, invigorating menthol green", common_pairings: ["Chocolate", "Lavender", "Eucalyptus", "Grapefruit"] },
  { name: "Eucalyptus", cas_number: "8000-48-4", category: "aromatic", note_type: "top", typical_percentage_range: { min: 2, max: 8 }, volatility: "high", description: "Camphoraceous, medicinal, penetrating fresh", common_pairings: ["Pine", "Mint", "Lemon", "Tea Tree"] },

  // MUSK
  { name: "White Musk", cas_number: "N/A-wmusk", category: "musk", note_type: "base", typical_percentage_range: { min: 3, max: 15 }, volatility: "low", description: "Clean, soft, skin-like, laundry-fresh warmth", common_pairings: ["Rose", "Iris", "Sandalwood", "Lily"] },
  { name: "Galaxolide", cas_number: "1222-05-5", category: "musk", note_type: "base", typical_percentage_range: { min: 2, max: 10 }, volatility: "low", description: "Sweet, clean, powdery synthetic musk", common_pairings: ["White Musk", "Aldehydes", "Iris", "Cedar"] },
  { name: "Cashmeran", cas_number: "33704-61-9", category: "musk", note_type: "base", typical_percentage_range: { min: 2, max: 10 }, volatility: "low", description: "Warm, spicy, musky, woody, cashmere-soft", common_pairings: ["Musk", "Sandalwood", "Iris", "Amber"] },
  { name: "Ambrette", cas_number: "6707-60-4", category: "musk", note_type: "base", typical_percentage_range: { min: 1, max: 8 }, volatility: "low", description: "Natural, wine-like, floral, musky seed", common_pairings: ["Rose", "Oud", "Sandalwood", "Patchouli"] },

  // AMBER
  { name: "Ambergris", cas_number: "N/A-amb", category: "amber", note_type: "base", typical_percentage_range: { min: 2, max: 10 }, volatility: "low", description: "Marine, sweet, earthy, deeply animalic precious note", common_pairings: ["Oud", "Sandalwood", "Vanilla", "Musk"] },
  { name: "Amber Accord", cas_number: "N/A-amba", category: "amber", note_type: "base", typical_percentage_range: { min: 3, max: 15 }, volatility: "low", description: "Warm, resinous, sweet, powdery golden warmth", common_pairings: ["Vanilla", "Labdanum", "Benzoin", "Sandalwood"] },
  { name: "Benzyl Benzoate", cas_number: "120-51-4", category: "amber", note_type: "base", typical_percentage_range: { min: 1, max: 5 }, volatility: "low", description: "Faint, balsamic, slightly sweet fixative", common_pairings: ["Benzoin", "Vanilla", "Musk", "Amber"] },

  // GREEN
  { name: "Galbanum", cas_number: "8023-91-4", category: "green", note_type: "top", typical_percentage_range: { min: 1, max: 6 }, volatility: "high", description: "Intensely green, bitter, sharp, leafy", common_pairings: ["Iris", "Rose", "Violet Leaf", "Hyacinth"] },
  { name: "Violet Leaf", cas_number: "8024-08-6", category: "green", note_type: "top", typical_percentage_range: { min: 1, max: 5 }, volatility: "high", description: "Intensely green, crisp, cucumber-like leaf", common_pairings: ["Iris", "Galbanum", "Cucumber", "Rose"] },
  { name: "Grass", cas_number: "N/A-grass", category: "green", note_type: "top", typical_percentage_range: { min: 1, max: 5 }, volatility: "high", description: "Fresh-cut grass, sweet, dewy green", common_pairings: ["Fig Leaf", "Violet Leaf", "Mint", "Bamboo"] },
  { name: "Ivy", cas_number: "N/A-ivy", category: "green", note_type: "top", typical_percentage_range: { min: 1, max: 4 }, volatility: "high", description: "Cool, waxy, green, slightly aquatic leaf", common_pairings: ["Grass", "Galbanum", "Fig Leaf", "Moss"] },

  // FRUITY
  { name: "Apple", cas_number: "N/A-apple", category: "fruity", note_type: "top", typical_percentage_range: { min: 2, max: 8 }, volatility: "high", description: "Crisp, sweet-tart, sparkling fruit", common_pairings: ["Rose", "Lily", "Bamboo", "Green Tea"] },
  { name: "Peach", cas_number: "N/A-peach", category: "fruity", note_type: "top", typical_percentage_range: { min: 2, max: 10 }, volatility: "high", description: "Soft, velvety, sweet, juicy stone fruit", common_pairings: ["Osmanthus", "Jasmine", "Rose", "Vanilla"] },
  { name: "Raspberry", cas_number: "N/A-rasp", category: "fruity", note_type: "top", typical_percentage_range: { min: 1, max: 6 }, volatility: "high", description: "Tart, sweet, vibrant red berry", common_pairings: ["Rose", "Vanilla", "Patchouli", "Chocolate"] },
  { name: "Blackcurrant", cas_number: "N/A-cassis", category: "fruity", note_type: "top", typical_percentage_range: { min: 1, max: 6 }, volatility: "high", description: "Tart, catty, green-fruity berry", common_pairings: ["Rose", "Peony", "Patchouli", "Musk"] },
  { name: "Pear", cas_number: "N/A-pear", category: "fruity", note_type: "top", typical_percentage_range: { min: 2, max: 8 }, volatility: "high", description: "Fresh, sweet, crisp, clean fruit", common_pairings: ["Magnolia", "Freesia", "Musk", "Cedar"] },
  { name: "Plum", cas_number: "N/A-plum", category: "fruity", note_type: "top", typical_percentage_range: { min: 1, max: 6 }, volatility: "medium", description: "Rich, dark, slightly boozy stone fruit", common_pairings: ["Rose", "Oud", "Amber", "Cinnamon"] },
  { name: "Cherry", cas_number: "N/A-cherry", category: "fruity", note_type: "top", typical_percentage_range: { min: 1, max: 6 }, volatility: "high", description: "Sweet, almond-tinged, juicy fruit", common_pairings: ["Almond", "Tonka Bean", "Vanilla", "Rose"] },
  { name: "Passion Fruit", cas_number: "N/A-passion", category: "fruity", note_type: "top", typical_percentage_range: { min: 1, max: 5 }, volatility: "high", description: "Tropical, tart, exotic, sulfurous-sweet fruit", common_pairings: ["Coconut", "Ylang Ylang", "Mango", "Jasmine"] },
  { name: "Mango", cas_number: "N/A-mango", category: "fruity", note_type: "top", typical_percentage_range: { min: 1, max: 5 }, volatility: "high", description: "Lush, tropical, sweet, creamy fruit", common_pairings: ["Passion Fruit", "Coconut", "Jasmine", "Vanilla"] },
  { name: "Lychee", cas_number: "N/A-lychee", category: "fruity", note_type: "top", typical_percentage_range: { min: 1, max: 5 }, volatility: "high", description: "Delicate, rosy, sweet exotic fruit", common_pairings: ["Rose", "Peony", "Magnolia", "Musk"] },

  // SPICY
  { name: "Cinnamon", cas_number: "8015-91-6", category: "spicy", note_type: "middle", typical_percentage_range: { min: 1, max: 6 }, volatility: "medium", description: "Warm, sweet, spicy bark with festive warmth", common_pairings: ["Orange", "Vanilla", "Clove", "Apple"] },
  { name: "Clove", cas_number: "8000-34-8", category: "spicy", note_type: "middle", typical_percentage_range: { min: 1, max: 5 }, volatility: "medium", description: "Warm, spicy, eugenol-rich, dental-aromatic", common_pairings: ["Cinnamon", "Orange", "Carnation", "Rose"] },
  { name: "Cardamom", cas_number: "8000-66-6", category: "spicy", note_type: "top", typical_percentage_range: { min: 1, max: 6 }, volatility: "high", description: "Fresh, aromatic, eucalyptus-spicy, slightly sweet", common_pairings: ["Coffee", "Rose", "Oud", "Saffron"] },
  { name: "Black Pepper", cas_number: "8006-82-4", category: "spicy", note_type: "top", typical_percentage_range: { min: 1, max: 5 }, volatility: "high", description: "Sharp, dry, warm, woody-spicy heat", common_pairings: ["Bergamot", "Vetiver", "Grapefruit", "Oud"] },
  { name: "Nutmeg", cas_number: "8008-45-5", category: "spicy", note_type: "middle", typical_percentage_range: { min: 1, max: 4 }, volatility: "medium", description: "Warm, sweet, woody-spicy, slightly narcotic", common_pairings: ["Cinnamon", "Vanilla", "Orange", "Lavender"] },
  { name: "Ginger", cas_number: "8007-08-7", category: "spicy", note_type: "top", typical_percentage_range: { min: 1, max: 6 }, volatility: "high", description: "Fresh, zesty, warm, slightly lemony spice", common_pairings: ["Lemon", "Bergamot", "Cardamom", "Vetiver"] },
  { name: "Saffron", cas_number: "N/A-saf", category: "spicy", note_type: "middle", typical_percentage_range: { min: 0.5, max: 4 }, volatility: "medium", description: "Metallic, leathery, warm, precious spice", common_pairings: ["Rose", "Oud", "Amber", "Leather"] },
  { name: "Star Anise", cas_number: "8007-70-3", category: "spicy", note_type: "middle", typical_percentage_range: { min: 1, max: 4 }, volatility: "medium", description: "Sweet, licorice-like, warm anise spice", common_pairings: ["Vanilla", "Cinnamon", "Orange", "Clove"] },

  // GOURMAND
  { name: "Caramel", cas_number: "N/A-car", category: "gourmand", note_type: "base", typical_percentage_range: { min: 2, max: 10 }, volatility: "low", description: "Sweet, burnt sugar, toffee warmth", common_pairings: ["Vanilla", "Coffee", "Praline", "Sea Salt"] },
  { name: "Chocolate", cas_number: "N/A-choc", category: "gourmand", note_type: "base", typical_percentage_range: { min: 2, max: 8 }, volatility: "low", description: "Rich, bitter-sweet, roasted cocoa depth", common_pairings: ["Vanilla", "Coffee", "Patchouli", "Orange"] },
  { name: "Coffee", cas_number: "8001-67-0", category: "gourmand", note_type: "middle", typical_percentage_range: { min: 2, max: 10 }, volatility: "medium", description: "Roasted, bitter, energizing, dark aromatic", common_pairings: ["Cardamom", "Vanilla", "Chocolate", "Leather"] },
  { name: "Honey", cas_number: "N/A-honey", category: "gourmand", note_type: "middle", typical_percentage_range: { min: 2, max: 8 }, volatility: "medium", description: "Sweet, waxy, animalic, golden nectar", common_pairings: ["Tobacco", "Rose", "Amber", "Vanilla"] },
  { name: "Praline", cas_number: "N/A-pra", category: "gourmand", note_type: "base", typical_percentage_range: { min: 1, max: 6 }, volatility: "low", description: "Nutty, caramelized, warm, toasted sweetness", common_pairings: ["Caramel", "Vanilla", "Almond", "Coffee"] },
  { name: "Almond", cas_number: "N/A-alm", category: "gourmand", note_type: "middle", typical_percentage_range: { min: 1, max: 6 }, volatility: "medium", description: "Nutty, marzipan, slightly bitter sweetness", common_pairings: ["Cherry", "Vanilla", "Tonka Bean", "Heliotrope"] },
  { name: "Coconut", cas_number: "N/A-coco", category: "gourmand", note_type: "middle", typical_percentage_range: { min: 2, max: 8 }, volatility: "medium", description: "Creamy, tropical, lactonic, sun-drenched sweetness", common_pairings: ["Vanilla", "Tuberose", "Ylang Ylang", "Sandalwood"] },

  // AQUATIC
  { name: "Sea Salt", cas_number: "N/A-salt", category: "aquatic", note_type: "top", typical_percentage_range: { min: 1, max: 5 }, volatility: "high", description: "Mineral, briny, clean oceanic sparkle", common_pairings: ["Marine Notes", "Driftwood", "Ambergris", "Caramel"] },
  { name: "Marine Notes", cas_number: "N/A-marine", category: "aquatic", note_type: "middle", typical_percentage_range: { min: 2, max: 8 }, volatility: "medium", description: "Oceanic, fresh, ozonic, seashore atmosphere", common_pairings: ["Sea Salt", "Driftwood", "Ambergris", "Musk"] },
  { name: "Seaweed", cas_number: "N/A-seaweed", category: "aquatic", note_type: "middle", typical_percentage_range: { min: 1, max: 4 }, volatility: "medium", description: "Green, iodic, oceanic, umami-like marine", common_pairings: ["Sea Salt", "Marine Notes", "Driftwood", "Vetiver"] },
  { name: "Water Lily", cas_number: "N/A-wlily", category: "aquatic", note_type: "middle", typical_percentage_range: { min: 2, max: 8 }, volatility: "medium", description: "Fresh, watery, delicate, clean floral-aquatic", common_pairings: ["Lotus", "Ozonic Notes", "Musk", "Green Tea"] },

  // LEATHER
  { name: "Suede", cas_number: "N/A-suede", category: "leather", note_type: "base", typical_percentage_range: { min: 2, max: 8 }, volatility: "low", description: "Soft, velvety, dry, elegant animal skin", common_pairings: ["Iris", "Violet", "Osmanthus", "Saffron"] },
  { name: "Castoreum", cas_number: "8023-83-4", category: "leather", note_type: "base", typical_percentage_range: { min: 0.5, max: 3 }, volatility: "low", description: "Animalic, leathery, warm, birch-tar depth", common_pairings: ["Leather", "Oud", "Labdanum", "Birch Tar"] },
  { name: "Birch Tar", cas_number: "8001-88-5", category: "leather", note_type: "base", typical_percentage_range: { min: 0.5, max: 4 }, volatility: "low", description: "Smoky, tarry, leathery, campfire-like", common_pairings: ["Birch", "Smoke", "Leather", "Vetiver"] },
  { name: "Smoke", cas_number: "N/A-smoke", category: "leather", note_type: "base", typical_percentage_range: { min: 1, max: 5 }, volatility: "low", description: "Campfire, bonfire, charred wood aromatic", common_pairings: ["Birch Tar", "Incense", "Oud", "Vetiver"] },

  // BALSAMIC
  { name: "Frankincense", cas_number: "8016-36-2", category: "balsamic", note_type: "base", typical_percentage_range: { min: 2, max: 12 }, volatility: "low", description: "Resinous, citrusy, sacred, church-incense warmth", common_pairings: ["Myrrh", "Sandalwood", "Rose", "Oud"] },
  { name: "Myrrh", cas_number: "8016-37-3", category: "balsamic", note_type: "base", typical_percentage_range: { min: 2, max: 8 }, volatility: "low", description: "Warm, balsamic, slightly medicinal, ancient resin", common_pairings: ["Frankincense", "Oud", "Rose", "Sandalwood"] },
  { name: "Elemi", cas_number: "8023-89-0", category: "balsamic", note_type: "top", typical_percentage_range: { min: 1, max: 6 }, volatility: "high", description: "Fresh, peppery, lemony, frankincense-like resin", common_pairings: ["Frankincense", "Lime", "Pink Pepper", "Lavender"] },
  { name: "Peru Balsam", cas_number: "8007-00-9", category: "balsamic", note_type: "base", typical_percentage_range: { min: 1, max: 6 }, volatility: "low", description: "Warm, vanillic, cinnamon-like, sweet balsam", common_pairings: ["Vanilla", "Benzoin", "Cinnamon", "Tonka Bean"] },
  { name: "Tolu Balsam", cas_number: "9000-64-0", category: "balsamic", note_type: "base", typical_percentage_range: { min: 1, max: 5 }, volatility: "low", description: "Sweet, warm, slightly hyacinth-like balsam", common_pairings: ["Peru Balsam", "Benzoin", "Vanilla", "Frankincense"] },

  // POWDERY
  { name: "Orris", cas_number: "8002-73-1", category: "powdery", note_type: "middle", typical_percentage_range: { min: 1, max: 8 }, volatility: "medium", description: "Powdery, violet-like, earthy, elegant root", common_pairings: ["Iris", "Violet", "Rose", "Suede"] },
  { name: "Heliotrope", cas_number: "N/A-helio", category: "powdery", note_type: "middle", typical_percentage_range: { min: 2, max: 8 }, volatility: "medium", description: "Sweet, almond, cherry-pie, powdery floral", common_pairings: ["Vanilla", "Almond", "Cherry", "Tonka Bean"] },
  { name: "Rice Powder", cas_number: "N/A-rice", category: "powdery", note_type: "base", typical_percentage_range: { min: 1, max: 5 }, volatility: "low", description: "Soft, clean, gentle, delicate powder", common_pairings: ["White Musk", "Iris", "Violet", "Aldehydes"] },

  // EARTHY
  { name: "Mushroom", cas_number: "N/A-mush", category: "earthy", note_type: "middle", typical_percentage_range: { min: 0.5, max: 3 }, volatility: "medium", description: "Damp, forest-floor, umami, mysterious earthiness", common_pairings: ["Soil", "Moss", "Vetiver", "Oud"] },
  { name: "Soil", cas_number: "N/A-soil", category: "earthy", note_type: "base", typical_percentage_range: { min: 0.5, max: 3 }, volatility: "low", description: "Petrichor, wet earth, rain-soaked ground", common_pairings: ["Mushroom", "Moss", "Vetiver", "Patchouli"] },
  { name: "Truffle", cas_number: "N/A-truf", category: "earthy", note_type: "base", typical_percentage_range: { min: 0.5, max: 2 }, volatility: "low", description: "Luxurious, dark, earthy, slightly sulfurous fungus", common_pairings: ["Mushroom", "Oud", "Leather", "Soil"] },
  { name: "Beetroot", cas_number: "N/A-beet", category: "earthy", note_type: "middle", typical_percentage_range: { min: 0.5, max: 3 }, volatility: "medium", description: "Sweet, earthy, mineral, soil-like root", common_pairings: ["Soil", "Iris", "Violet", "Rose"] },

  // SMOKY
  { name: "Cade", cas_number: "8013-10-3", category: "smoky", note_type: "base", typical_percentage_range: { min: 1, max: 5 }, volatility: "low", description: "Dry, smoky, tarry, rugged campfire wood", common_pairings: ["Birch Tar", "Leather", "Vetiver", "Labdanum"] },
  { name: "Incense", cas_number: "N/A-incense", category: "smoky", note_type: "base", typical_percentage_range: { min: 2, max: 10 }, volatility: "low", description: "Sacred, smoky, resinous, meditative atmosphere", common_pairings: ["Frankincense", "Myrrh", "Oud", "Sandalwood"] },

  // HERBAL
  { name: "Chamomile", cas_number: "8002-66-2", category: "herbal", note_type: "middle", typical_percentage_range: { min: 1, max: 6 }, volatility: "medium", description: "Sweet, apple-like, calming, gentle herbal", common_pairings: ["Lavender", "Honey", "Rose", "Bergamot"] },
  { name: "Clary Sage", cas_number: "8016-63-5", category: "herbal", note_type: "middle", typical_percentage_range: { min: 1, max: 6 }, volatility: "medium", description: "Warm, herbal, slightly narcotic, nutty sage", common_pairings: ["Lavender", "Bergamot", "Cedar", "Juniper"] },
  { name: "Artemisia", cas_number: "N/A-arte", category: "herbal", note_type: "top", typical_percentage_range: { min: 1, max: 4 }, volatility: "high", description: "Bitter, herbal, absinthe-like, aromatic green", common_pairings: ["Lavender", "Juniper", "Bergamot", "Rosemary"] },
  { name: "Immortelle", cas_number: "8023-99-2", category: "herbal", note_type: "middle", typical_percentage_range: { min: 1, max: 5 }, volatility: "medium", description: "Curry-like, honeyed, dried-flower herbal", common_pairings: ["Rose", "Honey", "Vanilla", "Tobacco"] },
  { name: "Hay", cas_number: "N/A-hay", category: "herbal", note_type: "middle", typical_percentage_range: { min: 1, max: 5 }, volatility: "medium", description: "Dry, coumarin-rich, sweet, sun-baked herbal", common_pairings: ["Tonka Bean", "Lavender", "Vanilla", "Tobacco"] },

  // ANIMALIC
  { name: "Civet", cas_number: "N/A-civet", category: "animalic", note_type: "base", typical_percentage_range: { min: 0.1, max: 1 }, volatility: "low", description: "Intense, warm, musky, fecal in concentration, floral in dilution", common_pairings: ["Rose", "Jasmine", "Musk", "Oud"] },
  { name: "Hyraceum", cas_number: "N/A-hyra", category: "animalic", note_type: "base", typical_percentage_range: { min: 0.1, max: 1 }, volatility: "low", description: "Complex, tobacco-like, animalic, dark warmth", common_pairings: ["Castoreum", "Oud", "Tobacco", "Leather"] },
];

// -------------------------------------------------------------------
// COMMUNITY SCENTS (12+ with valid percentages summing to 100)
// -------------------------------------------------------------------

export const communityScents: OSCFormula[] = [
  {
    id: "scent-001-rainy-forest",
    version: "1.0.0",
    name: "Petrichor Dreams",
    description: "The first drops of rain on a forest floor, releasing ancient earth memories and green vitality.",
    prompt: "A rainy forest at dawn",
    creator: "NatureLover42",
    created_at: "2025-12-15T10:30:00Z",
    ingredients: [
      { name: "Vetiver", cas_number: "8016-96-4", category: "woody", note_type: "base", percentage: 18, intensity: 8 },
      { name: "Cedar", cas_number: "8000-27-9", category: "woody", note_type: "base", percentage: 15, intensity: 7 },
      { name: "Soil", cas_number: "N/A-soil", category: "earthy", note_type: "base", percentage: 5, intensity: 6 },
      { name: "Galbanum", cas_number: "8023-91-4", category: "green", note_type: "top", percentage: 10, intensity: 7 },
      { name: "Pine", cas_number: "8002-09-3", category: "woody", note_type: "top", percentage: 12, intensity: 6 },
      { name: "Ozonic Notes", cas_number: "N/A-ozone", category: "fresh", note_type: "top", percentage: 8, intensity: 5 },
      { name: "Mushroom", cas_number: "N/A-mush", category: "earthy", note_type: "middle", percentage: 4, intensity: 4 },
      { name: "Violet Leaf", cas_number: "8024-08-6", category: "green", note_type: "top", percentage: 7, intensity: 5 },
      { name: "Cypress", cas_number: "8013-86-3", category: "woody", note_type: "middle", percentage: 9, intensity: 6 },
      { name: "White Musk", cas_number: "N/A-wmusk", category: "musk", note_type: "base", percentage: 12, intensity: 4 },
    ],
    evolution: {
      opening: ["Galbanum", "Pine", "Ozonic Notes", "Violet Leaf"],
      heart: ["Cypress", "Mushroom", "Vetiver"],
      drydown: ["Cedar", "Soil", "White Musk"],
    },
    accords: [
      { name: "Green Vitality", strength: 72, ingredients: ["Galbanum", "Violet Leaf", "Pine"] },
      { name: "Woody Foundation", strength: 85, ingredients: ["Vetiver", "Cedar", "Cypress"] },
    ],
    mood: ["Contemplative", "Fresh", "Natural"],
    season: ["Autumn", "Spring"],
    intensity: 6,
    longevity_hours: 8,
    sillage: "moderate",
    safety: { ifra_compliance: true, allergens: ["Linalool"], max_skin_concentration: 15, notes: "Patch test recommended" },
    tags: ["Forest", "Rain", "Earthy", "Green", "Woody"],
  },
  {
    id: "scent-002-grandma-kitchen",
    version: "1.0.0",
    name: "Nonna's Kitchen",
    description: "Warm spices, vanilla-drenched baking, and the golden glow of a holiday kitchen filled with love.",
    prompt: "Grandmother's kitchen on Christmas morning",
    creator: "ScentMemory",
    created_at: "2025-11-20T14:00:00Z",
    ingredients: [
      { name: "Vanilla", cas_number: "8024-06-4", category: "oriental", note_type: "base", percentage: 20, intensity: 8 },
      { name: "Cinnamon", cas_number: "8015-91-6", category: "spicy", note_type: "middle", percentage: 10, intensity: 7 },
      { name: "Nutmeg", cas_number: "8008-45-5", category: "spicy", note_type: "middle", percentage: 5, intensity: 5 },
      { name: "Orange", cas_number: "8008-57-9", category: "citrus", note_type: "top", percentage: 12, intensity: 6 },
      { name: "Clove", cas_number: "8000-34-8", category: "spicy", note_type: "middle", percentage: 4, intensity: 6 },
      { name: "Caramel", cas_number: "N/A-car", category: "gourmand", note_type: "base", percentage: 12, intensity: 7 },
      { name: "Honey", cas_number: "N/A-honey", category: "gourmand", note_type: "middle", percentage: 8, intensity: 5 },
      { name: "Almond", cas_number: "N/A-alm", category: "gourmand", note_type: "middle", percentage: 6, intensity: 4 },
      { name: "Tonka Bean", cas_number: "8046-22-8", category: "oriental", note_type: "base", percentage: 10, intensity: 6 },
      { name: "Sandalwood", cas_number: "8006-87-9", category: "woody", note_type: "base", percentage: 8, intensity: 5 },
      { name: "Ginger", cas_number: "8007-08-7", category: "spicy", note_type: "top", percentage: 5, intensity: 4 },
    ],
    evolution: {
      opening: ["Orange", "Cinnamon", "Ginger"],
      heart: ["Honey", "Clove", "Nutmeg", "Almond"],
      drydown: ["Vanilla", "Caramel", "Tonka Bean", "Sandalwood"],
    },
    accords: [
      { name: "Gourmand Sweetness", strength: 88, ingredients: ["Caramel", "Honey", "Almond"] },
      { name: "Oriental Warmth", strength: 75, ingredients: ["Vanilla", "Cinnamon", "Tonka Bean"] },
    ],
    mood: ["Cozy", "Nostalgic", "Warm"],
    season: ["Winter"],
    intensity: 8,
    longevity_hours: 10,
    sillage: "strong",
    safety: { ifra_compliance: true, allergens: ["Cinnamal", "Coumarin", "Eugenol"], max_skin_concentration: 12, notes: "Contains cinnamon - may irritate sensitive skin" },
    tags: ["Gourmand", "Holiday", "Baking", "Spicy", "Sweet"],
  },
  {
    id: "scent-003-old-books-coffee",
    version: "1.0.0",
    name: "The Reading Room",
    description: "Aged paper, leather-bound spines, and a steaming cup of dark roast in a sunlit library.",
    prompt: "The smell of old books and coffee",
    creator: "BookishNose",
    created_at: "2025-10-05T09:00:00Z",
    ingredients: [
      { name: "Coffee", cas_number: "8001-67-0", category: "gourmand", note_type: "middle", percentage: 18, intensity: 8 },
      { name: "Suede", cas_number: "N/A-suede", category: "leather", note_type: "base", percentage: 12, intensity: 6 },
      { name: "Vanilla", cas_number: "8024-06-4", category: "oriental", note_type: "base", percentage: 10, intensity: 5 },
      { name: "Cedar", cas_number: "8000-27-9", category: "woody", note_type: "base", percentage: 14, intensity: 7 },
      { name: "Cardamom", cas_number: "8000-66-6", category: "spicy", note_type: "top", percentage: 6, intensity: 5 },
      { name: "Tonka Bean", cas_number: "8046-22-8", category: "oriental", note_type: "base", percentage: 8, intensity: 5 },
      { name: "Patchouli", cas_number: "8014-09-3", category: "woody", note_type: "base", percentage: 10, intensity: 6 },
      { name: "Benzoin", cas_number: "9000-05-9", category: "oriental", note_type: "base", percentage: 6, intensity: 4 },
      { name: "Bergamot", cas_number: "8007-75-8", category: "citrus", note_type: "top", percentage: 8, intensity: 4 },
      { name: "White Musk", cas_number: "N/A-wmusk", category: "musk", note_type: "base", percentage: 8, intensity: 3 },
    ],
    evolution: {
      opening: ["Bergamot", "Cardamom", "Coffee"],
      heart: ["Coffee", "Suede", "Cedar"],
      drydown: ["Vanilla", "Tonka Bean", "Patchouli", "White Musk"],
    },
    accords: [
      { name: "Gourmand Sweetness", strength: 60, ingredients: ["Coffee"] },
      { name: "Woody Foundation", strength: 70, ingredients: ["Cedar", "Patchouli"] },
      { name: "Oriental Warmth", strength: 65, ingredients: ["Vanilla", "Tonka Bean", "Benzoin"] },
    ],
    mood: ["Intellectual", "Cozy", "Sophisticated"],
    season: ["Autumn", "Winter"],
    intensity: 7,
    longevity_hours: 9,
    sillage: "moderate",
    safety: { ifra_compliance: true, allergens: ["Coumarin", "Linalool"], max_skin_concentration: 15, notes: "Safe for general use" },
    tags: ["Coffee", "Leather", "Bookish", "Intellectual", "Cozy"],
  },
  {
    id: "scent-004-midnight-garden",
    version: "1.0.0",
    name: "Midnight Garden",
    description: "Night-blooming flowers release their intoxicating perfume under a crescent moon.",
    prompt: "A secret garden at midnight with night-blooming flowers",
    creator: "FloralMystic",
    created_at: "2025-09-18T22:00:00Z",
    ingredients: [
      { name: "Tuberose", cas_number: "8024-55-3", category: "floral", note_type: "middle", percentage: 18, intensity: 9 },
      { name: "Jasmine", cas_number: "8022-96-6", category: "floral", note_type: "middle", percentage: 15, intensity: 8 },
      { name: "Gardenia", cas_number: "N/A-gar", category: "floral", note_type: "middle", percentage: 10, intensity: 7 },
      { name: "Ylang Ylang", cas_number: "8006-81-3", category: "floral", note_type: "middle", percentage: 8, intensity: 6 },
      { name: "Neroli", cas_number: "8016-38-4", category: "floral", note_type: "top", percentage: 7, intensity: 5 },
      { name: "Sandalwood", cas_number: "8006-87-9", category: "woody", note_type: "base", percentage: 12, intensity: 6 },
      { name: "White Musk", cas_number: "N/A-wmusk", category: "musk", note_type: "base", percentage: 10, intensity: 5 },
      { name: "Benzoin", cas_number: "9000-05-9", category: "oriental", note_type: "base", percentage: 5, intensity: 4 },
      { name: "Bergamot", cas_number: "8007-75-8", category: "citrus", note_type: "top", percentage: 8, intensity: 4 },
      { name: "Violet Leaf", cas_number: "8024-08-6", category: "green", note_type: "top", percentage: 7, intensity: 3 },
    ],
    evolution: {
      opening: ["Neroli", "Bergamot", "Violet Leaf"],
      heart: ["Tuberose", "Jasmine", "Gardenia", "Ylang Ylang"],
      drydown: ["Sandalwood", "White Musk", "Benzoin"],
    },
    accords: [
      { name: "Floral Bouquet", strength: 95, ingredients: ["Tuberose", "Jasmine", "Gardenia", "Ylang Ylang", "Neroli"] },
    ],
    mood: ["Romantic", "Mysterious", "Sensual"],
    season: ["Summer", "Spring"],
    intensity: 9,
    longevity_hours: 12,
    sillage: "enormous",
    safety: { ifra_compliance: true, allergens: ["Linalool", "Benzyl Benzoate", "Farnesol"], max_skin_concentration: 10, notes: "Very potent - use sparingly" },
    tags: ["White Floral", "Night", "Romantic", "Opulent", "Garden"],
  },
  {
    id: "scent-005-ocean-cliff",
    version: "1.0.0",
    name: "Cliff's Edge",
    description: "Standing on wind-swept cliffs above crashing waves, salt spray mingling with wild herbs.",
    prompt: "Ocean cliffs with crashing waves and wild herbs",
    creator: "CoastalBreeze",
    created_at: "2025-08-22T16:00:00Z",
    ingredients: [
      { name: "Sea Salt", cas_number: "N/A-salt", category: "aquatic", note_type: "top", percentage: 10, intensity: 7 },
      { name: "Marine Notes", cas_number: "N/A-marine", category: "aquatic", note_type: "middle", percentage: 14, intensity: 7 },
      { name: "Rosemary", cas_number: "8000-25-7", category: "aromatic", note_type: "top", percentage: 8, intensity: 6 },
      { name: "Bergamot", cas_number: "8007-75-8", category: "citrus", note_type: "top", percentage: 10, intensity: 5 },
      { name: "Lavender", cas_number: "8000-28-0", category: "floral", note_type: "top", percentage: 9, intensity: 5 },
      { name: "Clary Sage", cas_number: "8016-63-5", category: "herbal", note_type: "middle", percentage: 6, intensity: 4 },
      { name: "Driftwood", cas_number: "N/A-drift", category: "woody", note_type: "base", percentage: 12, intensity: 6 },
      { name: "Ambergris", cas_number: "N/A-amb", category: "amber", note_type: "base", percentage: 8, intensity: 5 },
      { name: "White Musk", cas_number: "N/A-wmusk", category: "musk", note_type: "base", percentage: 13, intensity: 4 },
      { name: "Cypress", cas_number: "8013-86-3", category: "woody", note_type: "middle", percentage: 10, intensity: 5 },
    ],
    evolution: {
      opening: ["Sea Salt", "Bergamot", "Rosemary", "Lavender"],
      heart: ["Marine Notes", "Clary Sage", "Cypress"],
      drydown: ["Driftwood", "Ambergris", "White Musk"],
    },
    accords: [
      { name: "Fresh Breeze", strength: 80, ingredients: ["Sea Salt", "Marine Notes", "Bergamot"] },
      { name: "Green Vitality", strength: 55, ingredients: ["Rosemary", "Clary Sage", "Lavender"] },
    ],
    mood: ["Energizing", "Free", "Wild"],
    season: ["Summer", "Spring"],
    intensity: 6,
    longevity_hours: 7,
    sillage: "moderate",
    safety: { ifra_compliance: true, allergens: ["Linalool", "Limonene"], max_skin_concentration: 20, notes: "Fresh and safe for daily wear" },
    tags: ["Aquatic", "Fresh", "Herbal", "Coastal", "Marine"],
  },
  {
    id: "scent-006-smoky-whiskey",
    version: "1.0.0",
    name: "Islay Fireside",
    description: "Peated whiskey in a heavy glass, leather armchairs, and a crackling fireplace on a Scottish evening.",
    prompt: "Smoky whiskey by a fireplace in a leather armchair",
    creator: "PeatAndSmoke",
    created_at: "2025-07-10T20:00:00Z",
    ingredients: [
      { name: "Smoke", cas_number: "N/A-smoke", category: "leather", note_type: "base", percentage: 10, intensity: 8 },
      { name: "Suede", cas_number: "N/A-suede", category: "leather", note_type: "base", percentage: 12, intensity: 7 },
      { name: "Oud", cas_number: "N/A-oud", category: "woody", note_type: "base", percentage: 8, intensity: 8 },
      { name: "Vanilla", cas_number: "8024-06-4", category: "oriental", note_type: "base", percentage: 10, intensity: 5 },
      { name: "Cade", cas_number: "8013-10-3", category: "smoky", note_type: "base", percentage: 6, intensity: 7 },
      { name: "Honey", cas_number: "N/A-honey", category: "gourmand", note_type: "middle", percentage: 7, intensity: 5 },
      { name: "Black Pepper", cas_number: "8006-82-4", category: "spicy", note_type: "top", percentage: 6, intensity: 6 },
      { name: "Bergamot", cas_number: "8007-75-8", category: "citrus", note_type: "top", percentage: 8, intensity: 4 },
      { name: "Cedar", cas_number: "8000-27-9", category: "woody", note_type: "base", percentage: 12, intensity: 6 },
      { name: "Labdanum", cas_number: "8016-26-0", category: "oriental", note_type: "base", percentage: 8, intensity: 6 },
      { name: "Tonka Bean", cas_number: "8046-22-8", category: "oriental", note_type: "base", percentage: 7, intensity: 4 },
      { name: "Patchouli", cas_number: "8014-09-3", category: "woody", note_type: "base", percentage: 6, intensity: 5 },
    ],
    evolution: {
      opening: ["Black Pepper", "Bergamot", "Smoke"],
      heart: ["Honey", "Suede", "Cade"],
      drydown: ["Oud", "Vanilla", "Cedar", "Labdanum", "Tonka Bean"],
    },
    accords: [
      { name: "Woody Foundation", strength: 80, ingredients: ["Oud", "Cedar", "Patchouli"] },
      { name: "Oriental Warmth", strength: 75, ingredients: ["Vanilla", "Labdanum", "Tonka Bean"] },
    ],
    mood: ["Bold", "Masculine", "Warm"],
    season: ["Winter", "Autumn"],
    intensity: 9,
    longevity_hours: 14,
    sillage: "strong",
    safety: { ifra_compliance: true, allergens: ["Coumarin", "Eugenol"], max_skin_concentration: 10, notes: "Strong projection - one spray goes a long way" },
    tags: ["Smoky", "Leather", "Whiskey", "Masculine", "Dark"],
  },
  {
    id: "scent-007-cherry-blossom",
    version: "1.0.0",
    name: "Hanami",
    description: "Cherry blossoms floating on a gentle spring breeze, delicate and fleeting, with green tea warmth.",
    prompt: "Cherry blossom trees in a Japanese garden during spring",
    creator: "SakuraDrift",
    created_at: "2025-06-01T08:00:00Z",
    ingredients: [
      { name: "Cherry", cas_number: "N/A-cherry", category: "fruity", note_type: "top", percentage: 12, intensity: 5 },
      { name: "Rose", cas_number: "8007-01-0", category: "floral", note_type: "middle", percentage: 14, intensity: 6 },
      { name: "Peony", cas_number: "N/A-peo", category: "floral", note_type: "middle", percentage: 12, intensity: 5 },
      { name: "Green Tea", cas_number: "N/A-gtea", category: "fresh", note_type: "top", percentage: 10, intensity: 4 },
      { name: "Hinoki", cas_number: "N/A-hin", category: "woody", note_type: "base", percentage: 10, intensity: 5 },
      { name: "Lychee", cas_number: "N/A-lychee", category: "fruity", note_type: "top", percentage: 6, intensity: 4 },
      { name: "Bergamot", cas_number: "8007-75-8", category: "citrus", note_type: "top", percentage: 8, intensity: 4 },
      { name: "White Musk", cas_number: "N/A-wmusk", category: "musk", note_type: "base", percentage: 14, intensity: 3 },
      { name: "Sandalwood", cas_number: "8006-87-9", category: "woody", note_type: "base", percentage: 8, intensity: 4 },
      { name: "Rice Powder", cas_number: "N/A-rice", category: "powdery", note_type: "base", percentage: 6, intensity: 3 },
    ],
    evolution: {
      opening: ["Cherry", "Bergamot", "Green Tea", "Lychee"],
      heart: ["Rose", "Peony"],
      drydown: ["Hinoki", "White Musk", "Sandalwood", "Rice Powder"],
    },
    accords: [
      { name: "Floral Bouquet", strength: 70, ingredients: ["Rose", "Peony"] },
      { name: "Fresh Breeze", strength: 60, ingredients: ["Green Tea", "Bergamot", "Cherry"] },
    ],
    mood: ["Delicate", "Serene", "Romantic"],
    season: ["Spring"],
    intensity: 4,
    longevity_hours: 6,
    sillage: "intimate",
    safety: { ifra_compliance: true, allergens: ["Linalool", "Geraniol"], max_skin_concentration: 20, notes: "Very gentle, suitable for sensitive skin" },
    tags: ["Floral", "Japanese", "Cherry Blossom", "Delicate", "Spring"],
  },
  {
    id: "scent-008-desert-night",
    version: "1.0.0",
    name: "Saharan Starlight",
    description: "Cool desert air after sundown, warm sand releasing heat, distant incense from a Bedouin camp.",
    prompt: "A clear desert night under a sky full of stars",
    creator: "DuneWalker",
    created_at: "2025-05-15T23:00:00Z",
    ingredients: [
      { name: "Frankincense", cas_number: "8016-36-2", category: "balsamic", note_type: "base", percentage: 15, intensity: 8 },
      { name: "Saffron", cas_number: "N/A-saf", category: "spicy", note_type: "middle", percentage: 5, intensity: 7 },
      { name: "Oud", cas_number: "N/A-oud", category: "woody", note_type: "base", percentage: 10, intensity: 8 },
      { name: "Rose", cas_number: "8007-01-0", category: "floral", note_type: "middle", percentage: 10, intensity: 6 },
      { name: "Amber Accord", cas_number: "N/A-amba", category: "amber", note_type: "base", percentage: 14, intensity: 7 },
      { name: "Myrrh", cas_number: "8016-37-3", category: "balsamic", note_type: "base", percentage: 8, intensity: 6 },
      { name: "Cardamom", cas_number: "8000-66-6", category: "spicy", note_type: "top", percentage: 7, intensity: 5 },
      { name: "Sandalwood", cas_number: "8006-87-9", category: "woody", note_type: "base", percentage: 12, intensity: 6 },
      { name: "Incense", cas_number: "N/A-incense", category: "smoky", note_type: "base", percentage: 8, intensity: 7 },
      { name: "Bergamot", cas_number: "8007-75-8", category: "citrus", note_type: "top", percentage: 6, intensity: 4 },
      { name: "Black Pepper", cas_number: "8006-82-4", category: "spicy", note_type: "top", percentage: 5, intensity: 5 },
    ],
    evolution: {
      opening: ["Cardamom", "Bergamot", "Black Pepper", "Saffron"],
      heart: ["Rose", "Frankincense", "Saffron"],
      drydown: ["Oud", "Amber Accord", "Myrrh", "Sandalwood", "Incense"],
    },
    accords: [
      { name: "Oriental Warmth", strength: 90, ingredients: ["Frankincense", "Amber Accord", "Saffron", "Myrrh"] },
      { name: "Woody Foundation", strength: 65, ingredients: ["Oud", "Sandalwood"] },
    ],
    mood: ["Mystical", "Warm", "Exotic"],
    season: ["Winter", "Autumn"],
    intensity: 9,
    longevity_hours: 16,
    sillage: "enormous",
    safety: { ifra_compliance: true, allergens: ["Limonene", "Linalool"], max_skin_concentration: 8, notes: "Very concentrated - apply to pulse points only" },
    tags: ["Oriental", "Desert", "Incense", "Oud", "Mystical"],
  },
  {
    id: "scent-009-tropical-sunset",
    version: "1.0.0",
    name: "Golden Hour",
    description: "Tropical fruits and coconut cream as the sun paints the sky in mango and passion fruit hues.",
    prompt: "Tropical sunset on a beach with coconut and exotic fruits",
    creator: "IslandVibes",
    created_at: "2025-04-20T18:30:00Z",
    ingredients: [
      { name: "Coconut", cas_number: "N/A-coco", category: "gourmand", note_type: "middle", percentage: 15, intensity: 7 },
      { name: "Mango", cas_number: "N/A-mango", category: "fruity", note_type: "top", percentage: 10, intensity: 6 },
      { name: "Passion Fruit", cas_number: "N/A-passion", category: "fruity", note_type: "top", percentage: 8, intensity: 5 },
      { name: "Ylang Ylang", cas_number: "8006-81-3", category: "floral", note_type: "middle", percentage: 10, intensity: 6 },
      { name: "Vanilla", cas_number: "8024-06-4", category: "oriental", note_type: "base", percentage: 14, intensity: 6 },
      { name: "Sandalwood", cas_number: "8006-87-9", category: "woody", note_type: "base", percentage: 10, intensity: 5 },
      { name: "Lime", cas_number: "8008-26-2", category: "citrus", note_type: "top", percentage: 8, intensity: 5 },
      { name: "Tuberose", cas_number: "8024-55-3", category: "floral", note_type: "middle", percentage: 7, intensity: 5 },
      { name: "White Musk", cas_number: "N/A-wmusk", category: "musk", note_type: "base", percentage: 10, intensity: 3 },
      { name: "Sea Salt", cas_number: "N/A-salt", category: "aquatic", note_type: "top", percentage: 4, intensity: 3 },
      { name: "Caramel", cas_number: "N/A-car", category: "gourmand", note_type: "base", percentage: 4, intensity: 4 },
    ],
    evolution: {
      opening: ["Mango", "Passion Fruit", "Lime", "Sea Salt"],
      heart: ["Coconut", "Ylang Ylang", "Tuberose"],
      drydown: ["Vanilla", "Sandalwood", "White Musk", "Caramel"],
    },
    accords: [
      { name: "Gourmand Sweetness", strength: 70, ingredients: ["Coconut", "Caramel"] },
      { name: "Floral Bouquet", strength: 55, ingredients: ["Ylang Ylang", "Tuberose"] },
    ],
    mood: ["Joyful", "Tropical", "Carefree"],
    season: ["Summer"],
    intensity: 6,
    longevity_hours: 8,
    sillage: "moderate",
    safety: { ifra_compliance: true, allergens: ["Linalool", "Benzyl Benzoate"], max_skin_concentration: 18, notes: "Perfect for warm weather" },
    tags: ["Tropical", "Coconut", "Fruity", "Beach", "Summer"],
  },
  {
    id: "scent-010-velvet-noir",
    version: "1.0.0",
    name: "Velvet Noir",
    description: "Dark chocolate, espresso, and black orchid wrapped in a cloak of oud and amber.",
    prompt: "A luxurious evening at a dimly lit velvet lounge",
    creator: "NightOwl",
    created_at: "2025-03-08T21:00:00Z",
    ingredients: [
      { name: "Chocolate", cas_number: "N/A-choc", category: "gourmand", note_type: "base", percentage: 10, intensity: 7 },
      { name: "Coffee", cas_number: "8001-67-0", category: "gourmand", note_type: "middle", percentage: 12, intensity: 8 },
      { name: "Oud", cas_number: "N/A-oud", category: "woody", note_type: "base", percentage: 10, intensity: 8 },
      { name: "Amber Accord", cas_number: "N/A-amba", category: "amber", note_type: "base", percentage: 12, intensity: 6 },
      { name: "Vanilla", cas_number: "8024-06-4", category: "oriental", note_type: "base", percentage: 10, intensity: 5 },
      { name: "Rose", cas_number: "8007-01-0", category: "floral", note_type: "middle", percentage: 8, intensity: 5 },
      { name: "Black Pepper", cas_number: "8006-82-4", category: "spicy", note_type: "top", percentage: 5, intensity: 5 },
      { name: "Bergamot", cas_number: "8007-75-8", category: "citrus", note_type: "top", percentage: 7, intensity: 4 },
      { name: "Patchouli", cas_number: "8014-09-3", category: "woody", note_type: "base", percentage: 10, intensity: 6 },
      { name: "Saffron", cas_number: "N/A-saf", category: "spicy", note_type: "middle", percentage: 4, intensity: 6 },
      { name: "Cashmeran", cas_number: "33704-61-9", category: "musk", note_type: "base", percentage: 6, intensity: 4 },
      { name: "Cardamom", cas_number: "8000-66-6", category: "spicy", note_type: "top", percentage: 6, intensity: 5 },
    ],
    evolution: {
      opening: ["Bergamot", "Black Pepper", "Cardamom"],
      heart: ["Coffee", "Rose", "Saffron"],
      drydown: ["Chocolate", "Oud", "Amber Accord", "Vanilla", "Patchouli"],
    },
    accords: [
      { name: "Gourmand Sweetness", strength: 75, ingredients: ["Chocolate", "Coffee"] },
      { name: "Woody Foundation", strength: 70, ingredients: ["Oud", "Patchouli"] },
      { name: "Oriental Warmth", strength: 65, ingredients: ["Amber Accord", "Vanilla", "Saffron"] },
    ],
    mood: ["Luxurious", "Dark", "Seductive"],
    season: ["Winter", "Autumn"],
    intensity: 9,
    longevity_hours: 14,
    sillage: "strong",
    safety: { ifra_compliance: true, allergens: ["Coumarin", "Linalool"], max_skin_concentration: 10, notes: "Rich and opulent" },
    tags: ["Dark", "Gourmand", "Oud", "Luxurious", "Evening"],
  },
  {
    id: "scent-011-fresh-linen",
    version: "1.0.0",
    name: "Sunday Morning",
    description: "Clean white sheets drying in sunlight, cotton and aldehydes with a whisper of lavender.",
    prompt: "Fresh linen drying in warm sunshine on a Sunday morning",
    creator: "CleanSlate",
    created_at: "2025-02-14T10:00:00Z",
    ingredients: [
      { name: "Aldehydes", cas_number: "N/A-ald", category: "fresh", note_type: "top", percentage: 8, intensity: 5 },
      { name: "White Musk", cas_number: "N/A-wmusk", category: "musk", note_type: "base", percentage: 20, intensity: 5 },
      { name: "Lavender", cas_number: "8000-28-0", category: "floral", note_type: "top", percentage: 12, intensity: 5 },
      { name: "Bergamot", cas_number: "8007-75-8", category: "citrus", note_type: "top", percentage: 10, intensity: 4 },
      { name: "Lily of the Valley", cas_number: "N/A-lotv", category: "floral", note_type: "middle", percentage: 10, intensity: 4 },
      { name: "Cedar", cas_number: "8000-27-9", category: "woody", note_type: "base", percentage: 10, intensity: 4 },
      { name: "Iris", cas_number: "8002-73-1", category: "floral", note_type: "middle", percentage: 8, intensity: 4 },
      { name: "Galaxolide", cas_number: "1222-05-5", category: "musk", note_type: "base", percentage: 8, intensity: 3 },
      { name: "Ozonic Notes", cas_number: "N/A-ozone", category: "fresh", note_type: "top", percentage: 6, intensity: 3 },
      { name: "Pear", cas_number: "N/A-pear", category: "fruity", note_type: "top", percentage: 8, intensity: 3 },
    ],
    evolution: {
      opening: ["Aldehydes", "Bergamot", "Lavender", "Ozonic Notes", "Pear"],
      heart: ["Lily of the Valley", "Iris"],
      drydown: ["White Musk", "Cedar", "Galaxolide"],
    },
    accords: [
      { name: "Fresh Breeze", strength: 85, ingredients: ["Aldehydes", "Ozonic Notes", "Bergamot"] },
      { name: "Floral Bouquet", strength: 55, ingredients: ["Lavender", "Lily of the Valley", "Iris"] },
    ],
    mood: ["Clean", "Calm", "Bright"],
    season: ["Spring", "Summer"],
    intensity: 3,
    longevity_hours: 6,
    sillage: "intimate",
    safety: { ifra_compliance: true, allergens: ["Linalool", "Limonene"], max_skin_concentration: 25, notes: "Very safe, ideal for everyday wear" },
    tags: ["Clean", "Fresh", "Linen", "Musk", "Light"],
  },
  {
    id: "scent-012-enchanted-moss",
    version: "1.0.0",
    name: "Moss Cathedral",
    description: "An ancient stone church overgrown with moss and ivy, frankincense lingering from centuries of worship.",
    prompt: "An abandoned medieval cathedral covered in moss with lingering incense",
    creator: "RuinExplorer",
    created_at: "2025-01-05T15:00:00Z",
    ingredients: [
      { name: "Incense", cas_number: "N/A-incense", category: "smoky", note_type: "base", percentage: 14, intensity: 8 },
      { name: "Frankincense", cas_number: "8016-36-2", category: "balsamic", note_type: "base", percentage: 12, intensity: 7 },
      { name: "Ivy", cas_number: "N/A-ivy", category: "green", note_type: "top", percentage: 8, intensity: 5 },
      { name: "Vetiver", cas_number: "8016-96-4", category: "woody", note_type: "base", percentage: 12, intensity: 7 },
      { name: "Soil", cas_number: "N/A-soil", category: "earthy", note_type: "base", percentage: 5, intensity: 5 },
      { name: "Cedar", cas_number: "8000-27-9", category: "woody", note_type: "base", percentage: 10, intensity: 6 },
      { name: "Galbanum", cas_number: "8023-91-4", category: "green", note_type: "top", percentage: 7, intensity: 5 },
      { name: "Myrrh", cas_number: "8016-37-3", category: "balsamic", note_type: "base", percentage: 8, intensity: 6 },
      { name: "Elemi", cas_number: "8023-89-0", category: "balsamic", note_type: "top", percentage: 6, intensity: 4 },
      { name: "Labdanum", cas_number: "8016-26-0", category: "oriental", note_type: "base", percentage: 6, intensity: 5 },
      { name: "Bergamot", cas_number: "8007-75-8", category: "citrus", note_type: "top", percentage: 7, intensity: 3 },
      { name: "White Musk", cas_number: "N/A-wmusk", category: "musk", note_type: "base", percentage: 5, intensity: 3 },
    ],
    evolution: {
      opening: ["Elemi", "Bergamot", "Ivy", "Galbanum"],
      heart: ["Incense", "Frankincense"],
      drydown: ["Vetiver", "Cedar", "Myrrh", "Soil", "Labdanum", "White Musk"],
    },
    accords: [
      { name: "Green Vitality", strength: 50, ingredients: ["Ivy", "Galbanum"] },
      { name: "Woody Foundation", strength: 70, ingredients: ["Vetiver", "Cedar"] },
      { name: "Oriental Warmth", strength: 60, ingredients: ["Frankincense", "Myrrh", "Labdanum"] },
    ],
    mood: ["Mystical", "Ancient", "Solemn"],
    season: ["Autumn", "Winter"],
    intensity: 8,
    longevity_hours: 12,
    sillage: "strong",
    safety: { ifra_compliance: true, allergens: ["Limonene", "Linalool"], max_skin_concentration: 12, notes: "Complex and long-lasting" },
    tags: ["Incense", "Green", "Ancient", "Mystical", "Smoky"],
  },
  {
    id: "scent-013-lavender-field",
    version: "1.0.0",
    name: "Provence at Dusk",
    description: "Endless lavender fields stretching to the horizon, buzzing bees, and warm Provencal stone at golden hour.",
    prompt: "Walking through lavender fields in Provence at sunset",
    creator: "HerbGarden",
    created_at: "2024-12-18T17:00:00Z",
    ingredients: [
      { name: "Lavender", cas_number: "8000-28-0", category: "floral", note_type: "top", percentage: 22, intensity: 8 },
      { name: "Honey", cas_number: "N/A-honey", category: "gourmand", note_type: "middle", percentage: 8, intensity: 5 },
      { name: "Rosemary", cas_number: "8000-25-7", category: "aromatic", note_type: "top", percentage: 7, intensity: 5 },
      { name: "Tonka Bean", cas_number: "8046-22-8", category: "oriental", note_type: "base", percentage: 10, intensity: 5 },
      { name: "Clary Sage", cas_number: "8016-63-5", category: "herbal", note_type: "middle", percentage: 6, intensity: 4 },
      { name: "Bergamot", cas_number: "8007-75-8", category: "citrus", note_type: "top", percentage: 9, intensity: 4 },
      { name: "Sandalwood", cas_number: "8006-87-9", category: "woody", note_type: "base", percentage: 10, intensity: 5 },
      { name: "Coumarin", cas_number: "91-64-5", category: "oriental", note_type: "base", percentage: 6, intensity: 4 },
      { name: "White Musk", cas_number: "N/A-wmusk", category: "musk", note_type: "base", percentage: 10, intensity: 3 },
      { name: "Hay", cas_number: "N/A-hay", category: "herbal", note_type: "middle", percentage: 5, intensity: 3 },
      { name: "Geranium", cas_number: "8000-46-2", category: "floral", note_type: "middle", percentage: 7, intensity: 4 },
    ],
    evolution: {
      opening: ["Lavender", "Bergamot", "Rosemary"],
      heart: ["Honey", "Clary Sage", "Geranium", "Hay"],
      drydown: ["Tonka Bean", "Sandalwood", "Coumarin", "White Musk"],
    },
    accords: [
      { name: "Floral Bouquet", strength: 70, ingredients: ["Lavender", "Geranium"] },
      { name: "Green Vitality", strength: 55, ingredients: ["Rosemary", "Clary Sage", "Hay"] },
    ],
    mood: ["Peaceful", "Warm", "Nostalgic"],
    season: ["Summer", "Spring"],
    intensity: 6,
    longevity_hours: 8,
    sillage: "moderate",
    safety: { ifra_compliance: true, allergens: ["Linalool", "Coumarin", "Geraniol"], max_skin_concentration: 18, notes: "Classic aromatic profile" },
    tags: ["Lavender", "Herbal", "Provence", "Aromatic", "Warm"],
  },
];

// -------------------------------------------------------------------
// SCENT CARDS (derived from community scents)
// -------------------------------------------------------------------

export const scentCards: ScentCard[] = communityScents.map((scent, index) => ({
  id: scent.id,
  name: scent.name,
  description: scent.description,
  creator: scent.creator,
  creator_avatar: `/avatars/user-${(index % 6) + 1}.jpg`,
  ingredients: scent.ingredients,
  mood: scent.mood,
  season: scent.season,
  tags: scent.tags,
  likes: Math.floor(Math.random() * 500) + 50,
  remixes: Math.floor(Math.random() * 30) + 2,
  created_at: scent.created_at,
  intensity: scent.intensity,
}));

// -------------------------------------------------------------------
// USER PROFILE
// -------------------------------------------------------------------

export const mockUserProfile: UserProfile = {
  id: "user-001",
  name: "Alexandra Rosewood",
  username: "alexrosewood",
  avatar: "/avatars/user-1.jpg",
  bio: "Scent designer and fragrance enthusiast. Creating olfactory experiences that tell stories.",
  scent_genome: {
    citrus: 45,
    floral: 80,
    woody: 70,
    fresh: 55,
    oriental: 65,
    gourmand: 40,
    spicy: 50,
    aquatic: 30,
    green: 60,
    fruity: 35,
  },
  created_scents: scentCards.slice(0, 5),
  saved_scents: scentCards.slice(5, 10),
  stats: {
    scents_created: 24,
    total_likes: 1847,
    total_remixes: 89,
  },
  joined_date: "2024-06-15T00:00:00Z",
};

// -------------------------------------------------------------------
// EXAMPLE PROMPTS
// -------------------------------------------------------------------

export const examplePrompts = [
  "A rainy forest at dawn",
  "Grandmother's kitchen on Christmas morning",
  "The smell of old books and coffee",
  "A secret garden at midnight",
  "Ocean cliffs on a stormy day",
  "Walking through a spice market in Marrakech",
  "Fresh linen drying in sunshine",
  "A smoky whiskey bar at midnight",
  "Cherry blossoms in a Japanese garden",
  "An old library with leather armchairs",
  "Morning dew on lavender fields in Provence",
  "Campfire on a cold mountain night",
];

// -------------------------------------------------------------------
// DEFAULT FORMULA (used for the create page initial state)
// -------------------------------------------------------------------

export const defaultFormula: OSCFormula = communityScents[0];
